run:
  tests: true
  build-tags:
    - bench

linters-settings:
  depguard:
    list-type: blacklist
    include-go-root: true
    packages:
      - github.com/whatafunc/Golang_Otus_Labs/hw12_13_14_15_16_calendar/cmd
    packages-with-error-message:
      - package: github.com/whatafunc/Golang_Otus_Labs/hw12_13_14_15_16_calendar/cmd
        message: "Do not import cmd/ from non-cmd packages (clean architecture rule)"
  
  funlen:
    lines: 100
    statements: 50

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - dupl
        - gocyclo
        - gosec

linters:
  disable-all: true
  enable:
    - asciicheck
    - dogsled
    - dupl
    - bodyclose
    - durationcheck
    - errorlint
    - exhaustive
    - copyloopvar
    - gci
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gofmt
    - gofumpt
    - goheader
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - importas
    - ineffassign
    - lll
    - makezero
    - misspell
    - nestif
    - nilerr
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - staticcheck
    - stylecheck
    - tagliatelle
    - thelper
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace